package com.associago.app;

import org.springframework.boot.info.BuildProperties;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Exposes application metadata (version, build time) read from
 * META-INF/build-info.properties generated by the Gradle springBoot.buildInfo() task.
 */
@RestController
@RequestMapping("/api/v1/app")
public class AppInfoController {

    private final BuildProperties buildProperties;

    public AppInfoController(BuildProperties buildProperties) {
        this.buildProperties = buildProperties;
    }

    @GetMapping("/info")
    public ResponseEntity<Map<String, Object>> getInfo() {
        Map<String, Object> info = new LinkedHashMap<>();
        info.put("name", buildProperties.getName());
        info.put("version", buildProperties.getVersion());
        info.put("group", buildProperties.getGroup());
        info.put("buildTime", buildProperties.getTime() != null ? buildProperties.getTime().toString() : null);
        return ResponseEntity.ok(info);
    }
}
